### ISSUE TITLE
Think about Deployment

### ISSUE THREAD

**Issue by mgreci** [mrb1218/e-Sports#12]
If we deploy with Heroku, we will need to change the sqlite3 gem to another database (MySQL, Postgre). Any should work just double check it will work with our deployment option.

**Comment by njarvis77** [comment]
migrations were changed to fix deployment of application to heroku using postgresql database.  Seeding data will require a reset of the database with the command "heroku pg:reset DATABASE".  After reset, you will need to run "heroku run rake db:migrate db:seed" to re-migrate and re-seed the data properly.  The master branch is running on heroku at https://esportsnate.herokuapp.com
