### ISSUE TITLE
Working search bar

### ISSUE THREAD

**Issue by mgreci** [mrb1218/e-Sports#13]
search bar needs to work

**Comment by mgreci** [comment]
Maybe have some test data to get a visual of output

**Comment by mgreci** [comment]
We should decide on what results will look like.
A dropdown with top 5 results? Add a section to the current page so that whatever the user is viewing gets pushed down and the search results appear like they are part of the page

**Comment by ghost** [comment]
We will have to create a Search controller. Whenever a user types in
anything into the search bar and clicks submit, the input string will be
passed as a parameter to the Search controller. The controller will then
display any relevant data to the screen.

**Comment by mgreci** [comment]
Or we can doing the searching with JS

**Comment by ghost** [comment]
The rendering of the results can be done using JS. But the actual searching
part can only be done by sql queries that will search the DB and return the
results if found.

Sunil Pawar
Web Developer
Mentoring Institute
University of New Mexico

**Comment by mgreci** [comment]
This is working in that we can search by using the user's input as a regular expression and get back the matching leagues, teams, and players on a new page. Just move the search bar to the header instead of the footer
