### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by mgreci** [mrb1218/e-Sports#2]
Lets update the homepage to look better.

**Comment by mgreci** [comment]
youtube video example:
http://www.w3schools.com/html/html_youtube.asp

**Comment by mgreci** [comment]
I double checked and made some edits but the homepage will work if you add code to pages/index.html

**Comment by ghost** [comment]
Today I will be working on the pages/index.html to show the upcoming
matches and the YouTube videos!

Sunil Pawar
Web Developer
Mentoring Institute
University of New Mexico
