### ISSUE TITLE
Cannot create a user in heroku release?

### ISSUE THREAD

**Issue by mgreci** [mrb1218/e-Sports#24]
I tried to create an account in our heroku release and I was unable to. Also we re-seeded the database so I could not login with my original account...Thoughts?

**Comment by njarvis77** [comment]
I plan to talk to Ricardo today to get the Heroku thing figured out.  It has to be related to the database stuff being entered on that page.  Everything works fine running locally.

Thanks,

Nate

Sent from my iPhone

On Dec 8, 2016, at 1:01 PM, Matthew Greci <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried to create an account in our heroku release and I was unable to. Also we re-seeded the database so I could not login with my original account...Thoughts?

-

**Comment by mgreci** [comment]
This is fixed now. However, Nate's heroku will not push the latest code to heroku and images will not load.
