### ISSUE TITLE
Improve Teams page

### ISSUE THREAD

**Issue by mgreci** [mrb1218/e-Sports#7]
The page for displaying the Leagues, Teams, and Matches needs to be improved. Instead of a table, we should do something more fancy.

**Comment by mgreci** [comment]
I added some routing so Schedules goes to matches/schedule.html.erb, Results goes to matches/results.html.erb, and Prizes goes to leagues/prizes.html.erb

**Comment by ghost** [comment]
Sounds great, did we merged all that we have? For example the GUI and
master and then deployment on heroko. In case we need to show anything
today!

**Comment by mgreci** [comment]
I have not merged that yet. Work is still being done on GUI. Soon I will merge Master into GUI. Make sure everything merged properly. Then merge GUI into Master, then Release and push to Heroku.


On Dec 6, 2016, at 10:10 AM, Sunil Pawar <notifications@github.com<mailto:notifications@github.com>> wrote:

Sounds great, did we merged all that we have? For example the GUI and
master and then deployment on heroko. In case we need to show anything
today!
